apiVersion: v1
kind: Service
metadata:
  name: nexus-discovery-service
spec:
  type: NodePort
  selector:
    app: discovery
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090