spring:
  application:
    name: billing-batch
  batch:
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
datasource:
  meta:
    jdbc-url: ${DB_URL_META}
    username: ${DB_USER_META}
    password: ${DB_PASS_META}
    driver-class-name: ${DB_DRIVER_META}
  data:
    jdbc-url: ${DB_URL_DATA}
    username: ${DB_USER_DATA}
    password: ${DB_PASS_DATA}
    driver-class-name: ${DB_DRIVER_DATA}

server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

logging:
  level:
    org.springframework.security: DEBUG
billing:
  secret-key: ${SECRET_KEY}
