## Order Batch ConfigMap
## 테스트용 DB(test-db-service)를 바라봄
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-order-batch-config
  namespace: test
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_URL: jdbc:mariadb://test-db-service:3306/nexus
  DB_DRIVER: org.mariadb.jdbc.Driver
