apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-gateway-config
data:
  EUREKA_SERVICE_URL: "http://nexus-discovery-service:9090/eureka"
  FRONTEND_PROD_URL: "https://www.nexusscm.kro.kr"
  ROUTE_STATISTICS_ID: "statistics"
  ROUTE_STATISTICS_URI: "lb://NexusStatistics"
  ROUTE_POS_ID: "pos"
  ROUTE_POS_URI: "lb://NexusPos"
