apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: dwg0245/nexus-gateway:2.0
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: nexus-gateway-config
            - secretRef:
                name: nexus-gateway-secrets
