spring:
  application:
    name: NexusPos
  profiles:
    active: dev
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
